# Generated by Django 6.0.7 on 2026-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Medium', max_length=10),
        ),
    ]
