# Generated by Django 6.0.4 on 2026-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
