# Generated by Django 6.0.4 on 2026-07-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
    ]
