# Generated by Django 6.0.4 on 2026-07-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='has_3d_model',
            field=models.BooleanField(default=False),
        ),
    ]
