# Generated by Django 6.0.7 on 2026-07-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VISIT', 'Website Visit'), ('REGISTER', 'User Registration'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('SEARCH', 'Search'), ('FOOD_VIEW', 'Food View'), ('FOOD_CLICK', 'Food Click'), ('ADD_CART', 'Add to Cart'), ('REMOVE_CART', 'Remove from Cart'), ('CHECKOUT', 'Checkout'), ('ORDER', 'Order Placement'), ('REVIEW', 'Review Submission'), ('CONTACT', 'Contact Form Submission')], max_length=20)),
                ('search_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.category')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.food')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
