# Generated by Django 6.0.4 on 2026-07-23 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0003_alter_category_options_alter_food_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=16)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('session_start', 'Session Start'), ('user_register', 'User Register'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('menu_visit', 'Menu Visit'), ('category_click', 'Category Click'), ('food_view', 'Food View'), ('food_click', 'Food Click'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('cart_view', 'Cart View'), ('checkout_start', 'Checkout Start'), ('payment_attempt', 'Payment Attempt'), ('payment_success', 'Payment Success'), ('payment_failure', 'Payment Failure'), ('search', 'Search')], db_index=True, max_length=40)),
                ('page_path', models.CharField(blank=True, db_index=True, max_length=255)),
                ('search_term', models.CharField(blank=True, max_length=255)),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='Seconds the user spent on this page (sent on page leave)', null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='foods.category')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='foods.food')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.analyticssession')),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_s_user_id_25197d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['device_type'], name='analytics_s_device__697802_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session', 'event_type'], name='analytics_e_session_1f7d25_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['food', 'event_type'], name='analytics_e_food_id_a09879_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['page_path', 'created_at'], name='analytics_e_page_pa_df2ba0_idx'),
        ),
    ]
