# Generated by Django 6.0.4 on 2026-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='device_type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='page_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
