# Generated by Django 6.0.4 on 2026-07-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsevent_device_type_analyticsevent_page_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
