# Generated by Django 6.0.4 on 2026-07-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at']},
        ),
    ]
